version: '3'

services:
  southteenfc:
    env_file:
      - ./envfile
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 'aeroplanec/southteenfc:latest'
    ports:
      - '3000:3000'
  postgres:
    image: 'postgres:15'
    env_file:
      - ./envfile
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data