import "./login.css";
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface ReactLayoutProps {
  children: React.ReactNode
}

export default function LoginRootLayout(props:ReactLayoutProps){

  return (
    <html lang="en">
    <head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </head>
    <body>
      <div>{props.children}</div>
    </body>
    </html>
  )
}
